# Generated by Django 3.1.2 on 2020-10-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='', max_length=1024, verbose_name='Название бизнеса')),
                ('weights', models.CharField(default='0.0', max_length=1024, verbose_name='Веса в формате csv')),
            ],
        ),
    ]
