# Generated by Django 3.1.2 on 2020-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('Goods', 'Товары'), ('Service', 'Услуги')], default='Goods', max_length=10, verbose_name='Тип бизнеса'),
        ),
    ]
