# Generated by Django 3.1.2 on 2020-10-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='eng_name',
            field=models.CharField(default='', max_length=1024, verbose_name='Название на английском'),
        ),
    ]
