# Generated by Django 3.1.2 on 2020-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_eng_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=1024, verbose_name='Название категории')),
                ('eng_name', models.CharField(default='', max_length=1024, verbose_name='Название на английском')),
                ('weights', models.CharField(default='0.0', max_length=1024, verbose_name='Веса в формате csv')),
            ],
        ),
    ]
