# Generated by Django 3.1.2 on 2020-10-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_businesscategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessCategory',
            new_name='BusinessTag',
        ),
    ]
