# Generated by Django 3.1.2 on 2020-10-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20201031_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstag',
            name='category_name',
        ),
        migrations.AddField(
            model_name='businesstag',
            name='tag_name',
            field=models.CharField(default='', max_length=1024, verbose_name='Название тега'),
        ),
    ]
