# Generated by Django 3.1.2 on 2020-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20201031_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('goods', 'Товары'), ('service', 'Услуги')], default='goods', max_length=10, verbose_name='Тип бизнеса'),
        ),
    ]
