# Generated by Django 3.1.2 on 2020-10-31 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='City', max_length=256, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Широта левого верхнего угла')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Долгота левого верхнего угла')),
                ('parent_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='grid.grid', verbose_name='Родительская сетка')),
            ],
        ),
    ]
