# Generated by Django 3.1.2 on 2020-10-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='city_name',
            field=models.CharField(default='City', max_length=256, verbose_name='Название города'),
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='grid.grid', verbose_name='Родительская сетка')),
            ],
        ),
    ]
