# Generated by Django 3.1.2 on 2020-10-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='dist_to_underground',
            field=models.FloatField(default=0.0, verbose_name='Расстояние до ближайшей станции метро'),
        ),
        migrations.AddField(
            model_name='cell',
            name='population',
            field=models.IntegerField(default=0, verbose_name='Население в данноя ячейке'),
        ),
    ]
