# Generated by Django 3.1.2 on 2020-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_auto_20201031_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='population',
            field=models.IntegerField(default=0, verbose_name='Население в данной ячейке'),
        ),
    ]
