# Generated by Django 3.1.2 on 2020-10-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_auto_20201030_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Долгота левого верхнего угла'),
        ),
    ]
