# Generated by Django 3.1.2 on 2020-10-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_auto_20201031_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='children',
            field=models.IntegerField(default=0, verbose_name='Процент детей'),
        ),
    ]
