# Generated by Django 3.1.2 on 2020-11-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_cell_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='cell_traffic',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='children',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='dist_to_underground',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='elders',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='many_children',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='men',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='population',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='underground_traffic',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='young_parents',
        ),
        migrations.AddField(
            model_name='cell',
            name='info',
            field=models.CharField(default='', max_length=1024, verbose_name='Информация о клетке'),
        ),
    ]
